### ISSUE TITLE
Segfault in Position wrapping

### ISSUE THREAD

**Issue by InnocentBug** [SSAGESLabs/openmm-dlext#26]
I looked more closely on the installation on my local machine.

With OpenMM 7.7.0 (and other versions, compiled from scratch) and compiling open_dlext, I get a segfault running all examples of PySAGES with the CUDA platform.

I switched on `Debug` compilation and this is the top of the backtrace.
Seems like, we are getting invalid pointers to map the positions.

Any idea how to address this?

**Comment by InnocentBug** [comment]
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
DLExt::opaque (array=...) at /home/ludwig/git/openmm-dlext/openmmapi/include/DLExt.h:81
81	    return (void*)(array.getDevicePointer());
(gdb) bt
#0  DLExt::opaque (array=...) at /home/ludwig/git/openmm-dlext/openmmapi/include/DLExt.h:81
#1  0x00007ffe50097352 in DLExt::opaque (pdata=...) at /home/ludwig/git/openmm-dlext/openmmapi/include/DLExt.h:86
#2  0x00007ffe500bfcb3 in DLExt::opaque<OpenMM::CudaPlatform::PlatformData, DLExt::PositionsGetter> (view=..., p=...) at /home/ludwig/git/openmm-dlext/openmmapi/include/DLExt.h:110
#3  0x00007ffe500b3dfe in DLExt::opaque<DLExt::PositionsGetter> (view=..., p=...) at /home/ludwig/git/openmm-dlext/openmmapi/include/DLExt.h:118
#4  0x00007ffe500aba6f in DLExt::wrap<DLExt::PositionsGetter> (view=..., property=...) at /home/ludwig/git/openmm-dlext/openmmapi/include/DLExt.h:229
#5  0x00007ffe50097722 in DLExt::positions (view=...) at /home/ludwig/git/openmm-dlext/openmmapi/include/DLExt.h:252
#6  0x00007ffe500b3ac5 in DLExt::encapsulate<&DLExt::positions> (view=...) at /home/ludwig/git/openmm-dlext/wrappers/python/PyDLExt.h:21
#7  0x00007ffe500d98b5 in pybind11::detail::argument_loader<DLExt::ContextView const&>::call_impl<pybind11::capsule, pybind11::capsule (*&)(DLExt::ContextView const&), 0ul, pybind11::detail::void_type>(pybind11::capsule (*&)(DLExt::ContextView const&), std::integer_sequence<unsigned long, 0ul>, pybind11::detail::void_type&&) && (this=0x7fffffffb470, 
    f=@0x380da38: 0x7ffe500b3aa9 <DLExt::encapsulate<&DLExt::positions>(DLExt::ContextView const&)>) at /home/ludwig/git/openmm-dlext/build/_deps/pybind11-src/include/pybind11/cast.h:1441
#8  0x00007ffe500d252a in pybind11::detail::argument_loader<DLExt::ContextView const&>::call<pybind11::capsule, pybind11::detail::void_type, pybind11::capsule (*&)(DLExt::ContextView const&)>(pybind11::capsule (*&)(DLExt::ContextView const&)) && (this=0x7fffffffb470, f=@0x380da38: 0x7ffe500b3aa9 <DLExt::encapsulate<&DLExt::positions>(DLExt::ContextView const&)>)
    at /home/ludwig/git/openmm-dlext/build/_deps/pybind11-src/include/pybind11/cast.h:1410
#9  0x00007ffe500c8aee in pybind11::cpp_function::initialize<pybind11::capsule (*&)(DLExt::ContextView const&), pybind11::capsule, DLExt::ContextView const&, pybind11::name, pybind11::scope, pybind11::sibling>(pybind11::capsule (*&)(DLExt::ContextView const&), pybind11::capsule (*)(DLExt::ContextView const&), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::operator()(pybind11::detail::function_call&) const (this=0x0, call=...) at /home/ludwig/git/openmm-dlext/build/_deps/pybind11-src/include/pybind11/pybind11.h:249
#10 0x00007ffe500c8b6a in pybind11::cpp_function::initialize<pybind11::capsule (*&)(DLExt::ContextView const&), pybind11::capsule, DLExt::ContextView const&, pybind11::name, pybind11::scope, pybind11::sibling>(pybind11::capsule (*&)(DLExt::ContextView const&), pybind11::capsule (*)(DLExt::ContextView const&), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) () at /home/ludwig/git/openmm-dlext/build/_deps/pybind11-src/include/pybind11/pybind11.h:224
#11 0x00007ffe500a4c79 in pybind11::cpp_function::dispatcher (self=0x7ffea84fc8d0, args_in=0x7ffea851d700, kwargs_in=0x0)
    at /home/ludwig/git/openmm-dlext/build/_deps/pybind11-src/include/pybind11/pybind11.h:934
```

**Comment by InnocentBug** [comment]
Miniconda making me link to different libraries than I want to is to blame.

I am closing this for now, but we are working on cmake improvements to make this less likely to happen.
